HARDCODED_WEDDING_ITEMS = [
    {
        "id": "amz-wedding-5",
        "name": "JULEE Embroidered Semi-Stitched Lehenga Rani",
        "category": "Wedding",
        "price": 4100,
        "image_url": "https://m.media-amazon.com/images/I/310yjmDa5oL.jpg",
        "product_url": "https://www.amazon.in/JULEE-Embroidered-Semi-Stitched-Lehenga-Rani-ABC/dp/B0GC5886PX",
        "platform": "Amazon",
        "quality_rating": 4.7,
        "delivery_days": 2,
        "match_reason": "Amazon Top Pick",
        "gender": "Female"
    },
    {
        "id": "amz-wedding-6",
        "name": "Zeel Clothing Organza Semi-Stitched Floral Lehenga",
        "category": "Wedding",
        "price": 5500,
        "image_url": "https://m.media-amazon.com/images/I/51vX4Qt3l1L.jpg",
        "product_url": "https://www.amazon.in/Zeel-Clothing-Organza-Semi-Stitched-7614-DoveBlue-Wedding-Floral-Lehenga-New/dp/B09MBWVGX1",
        "platform": "Amazon",
        "quality_rating": 4.8,
        "delivery_days": 3,
        "match_reason": "Amazon Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-1",
        "name": "Sipeak Wear Better Women Maroon Kurta Sets",
        "category": "Wedding",
        "price": 1999,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JULY/23/bP6QmD6B_2ebd50eeb9254d9d9c72caf6f0f25c1f.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/sipeak+wear+better/sipeak-wear-better-women-maroon-kurta-sets/35940798/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 3,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-2",
        "name": "Sipeak Wear Better Women Red Kurta Sets",
        "category": "Wedding",
        "price": 1999,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JULY/23/berAzeVP_d126ca90dde149dfb00300d15db763e6.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/sipeak+wear+better/sipeak-wear-better-women-red-kurta-sets/35940797/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 4,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-3",
        "name": "Sipeak Wear Better Women Viscose Rayon Kurtas",
        "category": "Wedding",
        "price": 1999,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JULY/7/hl6Kd5ZA_1ab0b0fcd02d412ba323881f7f2cf690.jpg",
        "product_url": "https://www.myntra.com/kurtas/sipeak+wear+better/sipeak-wear-better-women-viscose-rayon-kurtas/35491313/buy",
        "platform": "Myntra",
        "quality_rating": 4.1,
        "delivery_days": 2,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-4",
        "name": "Fine Wear Printed Patola Cotton Silk Jacquard Sarees",
        "category": "Wedding",
        "price": 753,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/GxP4fpLt_95c18b220dff4f15bc6f20515f6f5820.jpg",
        "product_url": "https://www.myntra.com/sarees/fine+wear/fine-wear-printed-patola-cotton-silk-jacquard-sarees/41022234/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 5,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-5",
        "name": "Fine Wear Printed Patola Cotton Silk Jacquard Sarees Blue",
        "category": "Wedding",
        "price": 761,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/1ofDHBGJ_eae0c3178943405987c40f0937dec2ea.jpg",
        "product_url": "https://www.myntra.com/sarees/fine+wear/fine-wear-printed-patola-cotton-silk-jacquard-sarees/41022545/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 5,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-6",
        "name": "Fine Wear Woven Banarasi Cotton Silk Jacquard Sarees",
        "category": "Wedding",
        "price": 753,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/xiJhPydI_c53de86b672c41e1a9080364bfc4e40f.jpg",
        "product_url": "http://myntra.com/sarees/fine+wear/fine-wear-woven-banarasi-cotton-silk-jacquard-sarees/41025096/buy",
        "platform": "Myntra",
        "quality_rating": 4.9,
        "delivery_days": 3,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-7",
        "name": "Fine Wear Woven Patola Cotton Silk Jacquard Sarees Green",
        "category": "Wedding",
        "price": 753,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/jJ8R5Hdr_1683addda1ed4db2b836e7616255b7f1.jpg",
        "product_url": "https://www.myntra.com/sarees/fine+wear/fine-wear-woven-patola-cotton-silk-jacquard-sarees/41022802/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 4,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-8",
        "name": "Fine Wear Woven Patola Cotton Silk Jacquard Sarees Rust",
        "category": "Wedding",
        "price": 753,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/yoCYzk8N_be9006127e8d46bd9c69e53b6f25e10a.jpg",
        "product_url": "https://www.myntra.com/sarees/fine+wear/fine-wear-woven-patola-cotton-silk-jacquard-sarees/41022933/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 4,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-9",
        "name": "Bamsom Wear Women Sequinned Kurta with Palazzos & Dupatta",
        "category": "Wedding",
        "price": 734,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/DECEMBER/15/EdqdBkOb_91d41504e66249db8d40bfc8d1d4458b.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/bamsom+wear/bamsom-wear-women-regular-sequinned-kurta-with-palazzos--with-dupatta/38360221/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-10",
        "name": "Bafna Mens Wear Women Ethnic Motifs Woven Design Zari Saree",
        "category": "Wedding",
        "price": 749,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/OCTOBER/25/jUWtlz6c_d388b824bf174f0b930355ea61859e4e.jpg",
        "product_url": "https://www.myntra.com/sarees/bafna+mens+wear/bafna-mens-wear-women-ethnic-motifs-woven-design-zari-saree/37597633/buy",
        "platform": "Myntra",
        "quality_rating": 4.9,
        "delivery_days": 5,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-wedding-11",
        "name": "Bafna Mens Wear Women Woven Design Zari Saree",
        "category": "Wedding",
        "price": 749,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/OCTOBER/25/mPaBtPOc_1764fe60bd0a42dab7b0ae6eb516cbe9.jpg",
        "product_url": "https://www.myntra.com/sarees/bafna+mens+wear/bafna-mens-wear-women-woven-design-zari--saree/37597466/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 4,
        "match_reason": "Myntra Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-1",
        "name": "Vijay's Emerald Green Velvet Embroidered Jodhpuri Suit",
        "category": "Wedding",
        "price": 20999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/CTSD1440V_327_28-02-2026-14-23:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/jodhpuri-suit/vijay%27s-emerald-green-velvet-embroidered-jodhpuri-suit/UC149665.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 3,
        "match_reason": "Manyavar Top Pick",
        "gender": "Male"
    },
    {
        "id": "manyavar-wedding-2",
        "name": "Exquisite Beige Open Jodhpuri Suit",
        "category": "Wedding",
        "price": 20999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/CTSD1437-303-BEIGE-4_03-12-2025-11-19:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/jodhpuri-suit/exquisite-beige-open-jodhpuri-suit/UC151161.html",
        "platform": "Manyavar",
        "quality_rating": 4.6,
        "delivery_days": 4,
        "match_reason": "Manyavar Top Pick",
        "gender": "Male"
    },
    {
        "id": "manyavar-wedding-3",
        "name": "Velvety Charm Dark Blue Open Jodhpuri Suit",
        "category": "Wedding",
        "price": 20999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/CTSD1439V-306-Dark Blue-4-101_02-12-2025-13-23:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/jodhpuri-suit/velvety-charm-dark-blue-open-jodhpuri-suit/UC151163.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 2,
        "match_reason": "Manyavar Top Pick",
        "gender": "Male"
    },
    {
        "id": "manyavar-wedding-4",
        "name": "Velvety Maroon Elegance Bridal Lehenga",
        "category": "Wedding",
        "price": 54999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/UL5109V-407-MAROON1_22-07-2025-13-30:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/lehenga/velvety-maroon-elegance-bridal-lehenga/UC139174.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 5,
        "match_reason": "Manyavar Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-5",
        "name": "Purple Elegance Draped Saree",
        "category": "Wedding",
        "price": 12999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/PSB017_441-D. PURPLE_101.27825_04-03-2025-17-13:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/indo-western-dress-for-women/purple-elegance-draped-saree/UC135563.html",
        "platform": "Manyavar",
        "quality_rating": 4.8,
        "delivery_days": 3,
        "match_reason": "Manyavar Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-6",
        "name": "Elegant Warm White Open Sherwani",
        "category": "Wedding",
        "price": 36999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SHOS421_340-Warm White_101.3486_19-03-2025-12-34:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/sherwani/elegant-warm-white-open-sherwani/UC141298.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 4,
        "match_reason": "Manyavar Top Pick",
        "gender": "Male"
    },
    {
        "id": "manyavar-wedding-7",
        "name": "Classic Wine Bel Buti Patterned Bridal Saree",
        "category": "Wedding",
        "price": 11999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB17307_422-WINE_101.7284_26-12-2024-16-09:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/saree/classic-wine-bel-buti-patterned-bridal-saree/UC130998.html",
        "platform": "Manyavar",
        "quality_rating": 4.8,
        "delivery_days": 2,
        "match_reason": "Manyavar Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-8",
        "name": "Wine Delight Chiffon Lehenga",
        "category": "Wedding",
        "price": 11999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SKT4931_422-WINE_101.4657_23-12-2024-18-07:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/indo-western-dress-for-women/wine-delight-chiffon-lehenga/UC135193.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Manyavar Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-9",
        "name": "Wine Delight Chiffon Lehenga",
        "category": "Wedding",
        "price": 11999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SKT4931_422-WINE_101.4657_23-12-2024-18-07:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/indo-western-dress-for-women/wine-delight-chiffon-lehenga/UC135193.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Manyavar Top Pick",
        "gender": "Female"
    },
    {
        "id": "manyavar-wedding-10",
        "name": "Royal Maroon Jodhpuri Suit",
        "category": "Wedding",
        "price": 16999,
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/CTSD1404-322-Wine5:283x395?&amp;dpr=on,2",
        "product_url": "https://www.manyavar.com/en-in/jodhpuri-suit/royal-maroon-jodhpuri-suit/UC149239.html",
        "platform": "Manyavar",
        "quality_rating": 4.8,
        "delivery_days": 4,
        "match_reason": "Manyavar Top Pick",
        "gender": "Male"
    },
    {
        "id": "manyavar-wedding-w1",
        "name": "Elegant Red Bridal Lehenga",
        "category": "Wedding",
        "price": 39999,
        "product_url": "https://www.manyavar.com/en-in/lehenga/luxurious-red-bridal-lehenga/UC139176.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 3,
        "match_reason": "Bridal Favourite",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/UL5110V-425-RANI1_22-07-2025-13-30:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-wedding-w8",
        "name": "Peach Organza Wedding Lehenga",
        "category": "Wedding",
        "price": 19999,
        "product_url": "https://www.manyavar.com/en-in/lehenga/peach-organza-wedding-lehenga/UC139184.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Elegant Pick",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/UL5116_402-CREAM_101.3494_23-12-2024-12-00:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-wedding-w9",
        "name": "Champagne Gold Bridal Saree",
        "category": "Wedding",
        "price": 13999,
        "product_url": "https://www.manyavar.com/en-in/saree/champagne-gold-bridal-saree/UC131004.html",
        "platform": "Manyavar",
        "quality_rating": 4.6,
        "delivery_days": 4,
        "match_reason": "Classic Bridal",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SKT4892_426-T.BLUE_101.2634_28-07-2024-00-00:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-1",
        "name": "Wine Chinon Saree",
        "category": "Wedding",
        "price": 2999,
        "product_url": "https://www.manyavar.com/en-in/saree/wine-chinon-saree/UC156778.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Bridal Favourite",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19015-422-WINE-1-101_04-02-2026-07-42:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-2",
        "name": "Elegant Pink Mystique Saree",
        "category": "Wedding",
        "price": 5999,
        "product_url": "https://www.manyavar.com/en-in/saree/elegant-pink-mystique-saree/UC157997.html",
        "platform": "Manyavar",
        "quality_rating": 4.8,
        "delivery_days": 4,
        "match_reason": "Premium Pick",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19122-425-RANI-1-101_04-02-2026-08-53:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-3",
        "name": "Black Chic Draped Pre-draped Saree",
        "category": "Wedding",
        "price": 12999,
        "product_url": "https://www.manyavar.com/en-in/indo-western-dress-for-women/black-chic-draped-pre-draped-saree/UC155045.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 2,
        "match_reason": "Modern Bridal",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/PSB043-410-BLACK-1-101_05-02-2026-07-40:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-4",
        "name": "Rama Green Celebration Saree",
        "category": "Wedding",
        "price": 5999,
        "product_url": "https://www.manyavar.com/en-in/saree/rama-green-celebration-saree/UC156822.html",
        "platform": "Manyavar",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Festive Fav",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19032-433-RAMA GREEN-1-101_04-02-2026-11-47:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-5",
        "name": "Exquisite Beige Organza Saree",
        "category": "Wedding",
        "price": 8999,
        "product_url": "https://www.manyavar.com/en-in/saree/exquisite-beige-organza-saree/UC156860.html",
        "platform": "Manyavar",
        "quality_rating": 4.8,
        "delivery_days": 5,
        "match_reason": "Luxury Bridal",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19050-421-BEIGE-1-101_05-02-2026-06-34:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-6",
        "name": "Elegant Teal Blue Saree",
        "category": "Wedding",
        "price": 2499,
        "product_url": "https://www.manyavar.com/en-in/saree/elegant-teal-blue-saree/UC157993.html",
        "platform": "Manyavar",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Classy Pick",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19121-426-T.BLUE-1-101_04-02-2026-10-32:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-7",
        "name": "Fawn Elegance Net Palazzo Suit",
        "category": "Wedding",
        "price": 10999,
        "product_url": "https://www.manyavar.com/en-in/palazzo-suit/fawn-elegance-net-palazzo-suit/UC155054.html",
        "platform": "Manyavar",
        "quality_rating": 4.7,
        "delivery_days": 4,
        "match_reason": "Trending",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SAS8902-404-FAWN-1-101_05-02-2026-08-20:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-8",
        "name": "Purple Passion Net Palazzo Suit",
        "category": "Wedding",
        "price": 8999,
        "product_url": "https://www.manyavar.com/en-in/palazzo-suit/purple-passion-net-palazzo-suit/UC164086.html",
        "platform": "Manyavar",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Royal Choice",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SAS9010-413-PURPLE-1-101_05-02-2026-08-39:283x395?&amp;dpr=on,2"
    },
    {
        "id": "manyavar-w-9",
        "name": "Sublime Pink Festivity Banarasi Saree",
        "category": "Wedding",
        "price": 5999,
        "product_url": "https://www.manyavar.com/en-in/saree/sublime-pink-festivity-banarasi-saree/UC156847.html",
        "platform": "Manyavar",
        "quality_rating": 4.9,
        "delivery_days": 2,
        "match_reason": "Banarasi Classic",
        "gender": "Female",
        "image_url": "https://manyavar.scene7.com/is/image/manyavar/SB19044-414-PINK-6-101_04-02-2026-09-26:283x395?&amp;dpr=on,2"
    }
]

HARDCODED_OFFICE_ITEMS = [
    {
        "id": "myntra-office-1",
        "name": "Raymond Pure Cotton Solid Slim Fit Formal Shirt",
        "category": "Office",
        "price": 938,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/25365236/2023/10/31/0fc24136-3a2a-4488-96f8-35a8511dfd731698735621870-Raymond-Men-Shirts-6911698735621396-1.jpg",
        "product_url": "https://www.myntra.com/shirts/raymond/raymond-pure-cotton-solid-slim-fit-formal-shirt/25365236/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-2",
        "name": "Peter England Slim Fit Pure Cotton Formal Shirt",
        "category": "Office",
        "price": 953,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/24648176/2023/8/25/f7535889-9980-41c4-ae07-31b3a5f37b681692967864545PeterEnglandMenBrownSlimFitOpaqueFormalShirt1.jpg",
        "product_url": "https://www.myntra.com/shirts/peter+england/peter-england-slim-fit-pure-cotton-formal-shirt/24648176/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-3",
        "name": "Raymond Opaque Striped Pure Cotton Formal Shirt",
        "category": "Office",
        "price": 1088,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/26760266/2024/2/1/cc0ea4eb-d107-4276-b0bc-9b656f3c0fd61706769225074-Raymond-Men-Shirts-4321706769224680-1.jpg",
        "product_url": "https://www.myntra.com/shirts/raymond/raymond-opaque-striped-pure-cotton-formal-shirt/26760266/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-4",
        "name": "Raymond Slim Fit Pure Cotton Checked Formal Shirt",
        "category": "Office",
        "price": 1098,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/25365348/2023/10/31/489a6ec5-779d-479b-83ac-7da4d0bf8aa61698734207069-Raymond-Men-Shirts-9731698734206700-1.jpg",
        "product_url": "https://www.myntra.com/shirts/raymond/raymond-slim-fit-pure-cotton-checked-formal-shirt/25365348/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 3,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-5",
        "name": "Raymond Pure Cotton Slim Fit Floral Opaque Printed Formal Shirt",
        "category": "Office",
        "price": 1148,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/25942936/2023/12/5/7b78c74b-2f9a-4853-b3aa-384a06ee487c1701769761610-Raymond-Men-Shirts-4611701769761196-1.jpg",
        "product_url": "https://www.myntra.com/shirts/raymond/raymond-pure-cotton-slim-fit-floral-opaque-printed-formal-shirt/25942936/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-6",
        "name": "Raymond Men Checked Slim Fit Trousers",
        "category": "Office",
        "price": 1080,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/29314958/2024/5/22/3421440a-17e5-4e21-8f66-ba34ff2762e91716373178457-Raymond-Men-Trousers-1651716373177786-1.jpg",
        "product_url": "https://www.myntra.com/trousers/raymond/raymond-men-checked-slim-fit-trousers/29314958/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 4,
        "match_reason": "Top Brand Formal",
        "gender": "Male"
    },
    {
        "id": "myntra-office-7",
        "name": "Badland Men Classic Formal Shirt",
        "category": "Office",
        "price": 824,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/NOVEMBER/9/dxFzOu9b_d1ead12bb3804796aafb330bf0faa223.jpg",
        "product_url": "https://www.myntra.com/shirts/badland/badland-men-classic-formal-shirt/37869745/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 5,
        "match_reason": "Popular Choice",
        "gender": "Male"
    },
    {
        "id": "myntra-office-8",
        "name": "Highlander Men Slim Fit Shirt",
        "category": "Office",
        "price": 463,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/31/DNEIrJBb_594e4f0bbedf4e2ba016f6d3da4596eb.jpg",
        "product_url": "https://www.myntra.com/shirts/highlander/highlander-men-slim-fit-shirt/29684214/buy",
        "platform": "Myntra",
        "quality_rating": 4.3,
        "delivery_days": 2,
        "match_reason": "Popular Choice",
        "gender": "Male"
    },
    {
        "id": "myntra-office-9",
        "name": "Oquent Men Standard Fit Solid Spread Collar Casual Shirt",
        "category": "Office",
        "price": 387,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/SEPTEMBER/9/Qf7BKcA4_d509cca39bfd49acb21a36750ea0159d.jpg",
        "product_url": "https://www.myntra.com/shirts/oquent/oquent-men-standard-fit-solid-spread-collar-casual-shirt/36816587/buy",
        "platform": "Myntra",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Smart Casual",
        "gender": "Male"
    },
    {
        "id": "myntra-office-10",
        "name": "SZN Men Slim Fit Casual Shirt",
        "category": "Office",
        "price": 263,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/JANUARY/1/u9NZCz5D_3b6525c7421f4352b12d3638c4961d05.jpg",
        "product_url": "https://www.myntra.com/shirts/szn/szn-men-slim-fit-casual-shirt/39107202/buy",
        "platform": "Myntra",
        "quality_rating": 4.0,
        "delivery_days": 4,
        "match_reason": "Smart Casual",
        "gender": "Male"
    },
    {
        "id": "amazon-womens-office-3",
        "name": "Van Heusen Women Maroon Formal Shirt",
        "category": "Office",
        "price": 1400,
        "image_url": "https://m.media-amazon.com/images/I/410Xb00twFL.jpg",
        "product_url": "https://www.amazon.in/Van-Heusen-Womens-Regular-VWSFCRGBU46666_Maroon/dp/B0BF56R6Q8",
        "platform": "Amazon",
        "quality_rating": 4.6,
        "delivery_days": 4,
        "match_reason": "Premium Office Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-1",
        "name": "Jaey Women Solid Sleeveless Waistcoat Formal Top",
        "category": "Office",
        "price": 1936,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JUNE/2/xdh9aQsM_12ace2e253da466fbefab4473f3e88ce.jpg",
        "product_url": "https://www.myntra.com/tops/jaey/jaey-women-solid-sleeveless-waistcoat-formal-top/34666080/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 4,
        "match_reason": "Smart Formal Top",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-2",
        "name": "Her by Invictus Solid Pleated Formal Top",
        "category": "Office",
        "price": 716,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/30822653/2024/9/21/d5dfb2bd-bfa0-4bdf-a842-7d4e845330d51726918153390-V-Neck-Cuffed-Sleeves-Top-7101726918153002-1.jpg",
        "product_url": "https://www.myntra.com/tops/her+by+invictus/her-by-invictus-solid-pleated-top/30822653/buy",
        "platform": "Myntra",
        "quality_rating": 4.3,
        "delivery_days": 3,
        "match_reason": "Elegant Formal Top",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-3",
        "name": "Chemistry Solid Office Top",
        "category": "Office",
        "price": 740,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/27/b8RHZpe5_a8f03d2efd42462697a85dc2e33e823a.jpg",
        "product_url": "https://www.myntra.com/tops/chemistry/chemistry-top/40837871/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Womens Formal Pick",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-4",
        "name": "Dressberry V Neck Pleated Crinkle Top",
        "category": "Office",
        "price": 725,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/30898125/2024/9/23/db26918e-b543-4608-a8ec-b75e7f7537a71727083897027-V-Neck-Cuffed-Sleeves-Top-71727083896577-1.jpg",
        "product_url": "https://www.myntra.com/tops/dressberry/dressberry-v-neck-pleated-crinkle-textured-top/30898125/buy",
        "platform": "Myntra",
        "quality_rating": 4.1,
        "delivery_days": 4,
        "match_reason": "Trendy Formal",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-5",
        "name": "FableStreet Shirt Style Formal Top",
        "category": "Office",
        "price": 1137,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/productimage/2020/2/19/4e15ab1a-3a84-4665-94fd-73223655c65f1582087872889-1.jpg",
        "product_url": "https://www.myntra.com/tops/fablestreet/fablestreet-shirt-style-formal-top/11552822/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Premium Formal Top",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-6",
        "name": "Chemistry Crepe Formal Top",
        "category": "Office",
        "price": 696,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/33168854/2025/3/26/e20feacc-8546-4a91-a1bb-193e78824a1d1742971032736-Chemistry-Women-Tops-2051742971032272-1.jpg",
        "product_url": "https://www.myntra.com/tops/chemistry/chemistry-crepe-top/33168854/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Comfort Formal",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-7",
        "name": "All About You Formals High Rise Boot Cut Trousers",
        "category": "Office",
        "price": 748,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/FEBRUARY/6/jSMHPo0E_04c84ac0c20141ae937ae7782d8547ab.jpg",
        "product_url": "https://www.myntra.com/trousers/all+about+you+formals/all-about-you-formals-women-high-rise-boot-cut-trousers/32366318/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 5,
        "match_reason": "Stylish Workwear Pants",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-8",
        "name": "All About You Formals Boot Cut Trousers Khaki",
        "category": "Office",
        "price": 748,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/FEBRUARY/6/0KcUIbFg_f097a6d536364aec83b86a53c5a6a299.jpg",
        "product_url": "https://www.myntra.com/trousers/all+about+you+formals/all-about-you-formals-women-high-rise-boot-cut-trousers/32366317/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 5,
        "match_reason": "Stylish Workwear Pants",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-9",
        "name": "Chemistry Relaxed Straight Fit Pleated Trousers",
        "category": "Office",
        "price": 713,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/SEPTEMBER/22/ylKmweVh_48c0f4cd76f541ff9de42f714fa3dc12.jpg",
        "product_url": "https://www.myntra.com/trousers/chemistry/chemistry-women-relaxed-straight-fit-mid-rise-pleated-formal-trousers/37105317/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Relaxed Formal",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-office-10",
        "name": "All About You Formals Wrinkle Free Pleated Trousers",
        "category": "Office",
        "price": 747,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/OCTOBER/12/IasuNpZs_306e372c981a4bb4aa3bdb2c9ed46909.jpg",
        "product_url": "https://www.myntra.com/trousers/all+about+you+formals/all-about-you-formals-women-high-rise-wrinkle-free-pleated-trousers/37452721/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 2,
        "match_reason": "Zero Iron Formal Pants",
        "gender": "Female"
    },
    {
        "id": "bewakoof-woff-3",
        "name": "Women's Blue Striped Formal Shirt",
        "category": "Office",
        "price": 799,
        "product_url": "https://www.bewakoof.com/p/womens-blue-striped-oversized-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Corporate Pick",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-blue-striped-oversized-shirt-648460-1725602124-1.jpg"
    },
    {
        "id": "bewakoof-woff-9",
        "name": "Women's Black Cargo Joggers",
        "category": "Office",
        "price": 1249,
        "product_url": "https://www.bewakoof.com/p/womens-black-cargo-joggers",
        "platform": "Bewakoof",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Premium Office",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-black-cargo-joggers-633680-1708949907-1.jpg"
    }
]

HARDCODED_CASUAL_ITEMS = [
    {
        "id": "amazon-casual-1",
        "name": "TAGDO Men's Regular Crew T-shirt White",
        "category": "Casual",
        "price": 499,
        "image_url": "https://m.media-amazon.com/images/I/41kCrvlaJuL.jpg",
        "product_url": "https://www.amazon.in/TAGDO-Mens-Regular-Crew-RF-JQRD-Tshirt-2016-White-S/dp/B0DD3WH9S5",
        "platform": "Amazon",
        "quality_rating": 4.1,
        "delivery_days": 2,
        "match_reason": "Amazon Bestseller",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-1",
        "name": "Chrovel Men Textured Polo Collar Tshirts",
        "category": "Casual",
        "price": 590,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/APRIL/6/F6JRrFhM_7e79095391da433c8831b7722f24d65d.jpg",
        "product_url": "https://www.myntra.com/tshirts/chrovel/chrovel-men-textured-polo-collar-zip-closure-tshirts/41039411/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Myntra Daily Pick",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-2",
        "name": "Wrogn Men Pure Cotton Anti Fit Jeans",
        "category": "Casual",
        "price": 1385,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/23/w6QRBT8O_5e79e9c7e42342ce969436b73f213091.jpg",
        "product_url": "https://www.myntra.com/jeans/wrogn/wrogn-men-pure-cotton-anti-fit-jeans/38570442/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Myntra Premium Wear",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-3",
        "name": "The Indian Garage Co Men Green Check Casual Shirt",
        "category": "Casual",
        "price": 542,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/16190386/2021/11/27/c32bacf9-b432-405f-9ffa-b367fb31bf911637988409925-The-Indian-Garage-Co-Men-Shirts-6861637988409202-1.jpg",
        "product_url": "https://www.myntra.com/shirts/the+indian+garage+co/the-indian-garage-co-men-green-regular-fit-tartan-checks-opaque-checked-casual-shirt/16190386/buy",
        "platform": "Myntra",
        "quality_rating": 4.3,
        "delivery_days": 4,
        "match_reason": "Smart Casual Deal",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-4",
        "name": "Powerlook Men Light Beige Corduroy Track Pant",
        "category": "Casual",
        "price": 836,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JANUARY/25/0YyUSoCC_4a20a118ad6442d6be9641fcd16c7208.jpg",
        "product_url": "https://www.myntra.com/trousers/powerlook/powerlook-men-light-beige-corduroy-regular-fit-track-pant/32468906/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Myntra Top Selection",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-5",
        "name": "Roadster Men Black Pure Cotton Casual Shirt",
        "category": "Casual",
        "price": 433,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/18199958/2022/5/28/c2da2a49-5018-4227-9bcb-575386669f591653734630383-Mens-Casual-Solid-Shirt-6911653734629854-1.jpg",
        "product_url": "https://www.myntra.com/shirts/roadster/roadster-men-black-pure-cotton-casual-shirt/18199958/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 2,
        "match_reason": "Best Seller",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-6",
        "name": "Roadster Men Olive Green Cotton Casual Shirt",
        "category": "Casual",
        "price": 560,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/11904108/2020/7/14/869203dc-200a-4284-9d2d-a06fd5ea582d1594707585600-Roadster-Men-Shirts-1041594707583386-1.jpg",
        "product_url": "https://www.myntra.com/shirts/roadster/roadster-men-olive-green--cotton-casual-shirt/11904108/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 2,
        "match_reason": "Best Seller",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-7",
        "name": "Pepe Jeans Men Straight Fit Jeans",
        "category": "Casual",
        "price": 1438,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/19/nE6eSmzM_39ca99324e974026b94e393382be2405.jpg",
        "product_url": "https://www.myntra.com/jeans/pepe+jeans/pepe-jeans-men-holborne-straight-fit-mid-rise-light-fade-stretchable-jeans/39825875/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 5,
        "match_reason": "Premium Casuals",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-8",
        "name": "Highlander Men Solid Carpenter Cargo Pant",
        "category": "Casual",
        "price": 776,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/29877058/2024/6/1/5cb186fc-ed4d-4bf6-8811-613383a403c61717247400713HIGHLANDERMenLooseFitCargosTrousers1.jpg",
        "product_url": "https://www.myntra.com/trousers/highlander/highlander-men-solid-elasticated-carpenter-fit-cargo-pant/29877058/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Trending Choice",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-9",
        "name": "Pepe Jeans Men Brand Logo Printed T-shirt",
        "category": "Casual",
        "price": 699,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/FEBRUARY/26/jd11ZxFO_58cbbed495514b8691448f4f93d8d4ea.jpg",
        "product_url": "https://www.myntra.com/tshirts/pepe+jeans/pepe-jeans-men-brand-logo-printed-pure-cotton-slim-fit-t-shirt/40345592/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Myntra Bestseller",
        "gender": "Male"
    },
    {
        "id": "myntra-casual-10",
        "name": "Roadster Men White Classic Cotton Casual Shirt",
        "category": "Casual",
        "price": 489,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/17091614/2022/2/18/779ac019-8b8c-48f7-9c5e-b3e2fe3004b01645166457327-Men-White-Casual-Shirt-5731645166456476-1.jpg",
        "product_url": "https://www.myntra.com/shirts/roadster/roadster-men-white-classic-regular-fit-cotton-casual-shirt/17091614/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Best Seller",
        "gender": "Male"
    },
    {
        "id": "myntra-womens-casual-1",
        "name": "Okara Floral Printed Cotton Kurta",
        "category": "Casual",
        "price": 472,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/27/hmMuOIkG_f18403810bcc4f2896bee393cb67960c.jpg",
        "product_url": "https://www.myntra.com/kurtas/okara/okara-floral-printed-cotton-kurta/40954809/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Womens Daily Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-2",
        "name": "Sangria Printed Mandarin Collar Short Kurti",
        "category": "Casual",
        "price": 457,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/22425498/2023/3/28/8f638454-0451-47a8-bb93-de06952ad0df1679996112327-Women-Rani-Solid-Printed-Short-Kurti-2671679996111766-4.jpg",
        "product_url": "https://www.myntra.com/kurtis/sangria/sangria-printed-mandarin-collar-short-kurti/22425498/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 4,
        "match_reason": "Womens Daily Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-3",
        "name": "Meera Fab Floral Print Cotton Kurti",
        "category": "Casual",
        "price": 683,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/25/owXWwIIO_b7c18cf2253742e5a994cb2fbee11068.jpg",
        "product_url": "https://www.myntra.com/kurtis/meera+fab/meera-fab-floral-print-sweetheart-neck-pure-cotton-kurti-/40894040/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Womens Daily Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-4",
        "name": "Glitchez Solid Purple Polo Collar T-Shirt",
        "category": "Casual",
        "price": 515,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/APRIL/4/qeSRWXw5_21f97f11fbc8453db3cbec0822fb6d8c.jpg",
        "product_url": "https://www.myntra.com/tshirts/glitchez/glitchez-solid-purple-polo-collar-t-shirt/41135096/buy",
        "platform": "Myntra",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Womens Casual",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-5",
        "name": "Okara Floral Printed Cotton Kurta Pattern 2",
        "category": "Casual",
        "price": 472,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/27/rdgLbPsp_75a624437a2b41e7a2a1d156b0024f3d.jpg",
        "product_url": "https://www.myntra.com/kurtas/okara/okara-floral-printed-cotton-kurta/40954805/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Womens Daily Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-6",
        "name": "Syrish Embroidered Chikankari Handloom Kurti",
        "category": "Casual",
        "price": 894,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/23/bDQFuBTw_65c9f4d1ccd6418eb463ab7039635937.jpg",
        "product_url": "https://www.myntra.com/kurtis/syrish/syrish-embroidered-chikankari-handloom-chikankari-kurti/40860560/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 5,
        "match_reason": "Womens Premium Casual",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-7",
        "name": "Marks & Spencer Pure Cotton T-shirt",
        "category": "Casual",
        "price": 599,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/JANUARY/9/8YskxInt_26292e69ab13404199e81c1c21653e2a.jpg",
        "product_url": "https://www.myntra.com/tshirts/marks+%26+spencer/marks--spencer-pure-cotton-t-shirt/39272403/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 4,
        "match_reason": "Womens Premium Casual",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-8",
        "name": "SZN Women Graphic Printed Oversized T-shirt",
        "category": "Casual",
        "price": 299,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/MARCH/30/QZSpeW6g_8073d195d44f4dc5b0998c95edb4c466.jpg",
        "product_url": "https://www.myntra.com/tshirts/szn/szn-women-graphic-printed-oversized-cotton-t-shirt/41019652/buy",
        "platform": "Myntra",
        "quality_rating": 4.3,
        "delivery_days": 3,
        "match_reason": "Womens Trendy",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-9",
        "name": "The Roadster Life Co Wide Leg Stretch Jeans",
        "category": "Casual",
        "price": 849,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/DECEMBER/13/yU3NmUkv_a270d60015f541f89cd51daa068f469d.jpg",
        "product_url": "https://www.myntra.com/jeans/r.code+by+the+roadster+life+co./the-roadster-life-co-smart-wide-leg-high-rise-mildly-distressed-heavy/38611243/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Womens Trendy",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-casual-10",
        "name": "Zayla Women Comfort Wide Leg Stretchable Jeans",
        "category": "Casual",
        "price": 546,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2026/FEBRUARY/2/ANbeaZJL_c431c66b050d4d5ebda93e547f8c6b98.jpg",
        "product_url": "https://www.myntra.com/jeans/zayla/zayla-women-comfort-wide-leg-high-rise-stretchable-jeans/39790926/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 4,
        "match_reason": "Womens Trendy",
        "gender": "Female"
    },
    {
        "id": "amazon-womens-casual-3",
        "name": "FELISIA Printed Sleeves Stylish Western Top",
        "category": "Casual",
        "price": 499,
        "image_url": "https://m.media-amazon.com/images/I/41bfdoMrUOL.jpg",
        "product_url": "https://www.amazon.in/FELISIA-Printed-Sleeves-Stylish-Western/dp/B0GDRRRRYW",
        "platform": "Amazon",
        "quality_rating": 4.0,
        "delivery_days": 2,
        "match_reason": "Amazon Top Rated",
        "gender": "Female"
    },
    {
        "id": "bewakoof-casual-m1",
        "name": "Men's Black Oversized T-Shirt",
        "category": "Casual",
        "price": 519,
        "product_url": "https://www.bewakoof.com/p/mens-black-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Bestseller",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-black-oversized-t-shirt-468585-1643096583-1.jpg"
    },
    {
        "id": "bewakoof-casual-m2",
        "name": "Men's Blue Striped Oversized Shirt",
        "category": "Casual",
        "price": 499,
        "product_url": "https://www.bewakoof.com/p/mens-blue-striped-oversized-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Streetwear Pick",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-blue-striped-oversized-shirt-597301-1718599038-1.jpg"
    },
    {
        "id": "bewakoof-casual-m4",
        "name": "Men's Grey Joggers",
        "category": "Casual",
        "price": 1209,
        "product_url": "https://www.bewakoof.com/p/mens-grey-relaxed-fit-joggers",
        "platform": "Bewakoof",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Comfort Pick",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-grey-relaxed-fit-jogger-479484-1656191270-1.jpg"
    },
    {
        "id": "bewakoof-casual-m6",
        "name": "Men's Navy Polo T-Shirt",
        "category": "Casual",
        "price": 699,
        "product_url": "https://www.bewakoof.com/p/mens-navy-blue-polo-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Classic Polo",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-navy-blue-flatknit-polo-t-shirt-634392-1751614201-1.png"
    },
    {
        "id": "bewakoof-casual-m7",
        "name": "Men's Maroon Graphic Oversized Tee",
        "category": "Casual",
        "price": 299,
        "product_url": "https://www.bewakoof.com/p/mens-maroon-graphic-printed-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Cool Print",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-maroon-graphic-printed-oversized-t-shirt-509560-1658246480-1.jpg"
    },
    {
        "id": "bewakoof-casual-m8",
        "name": "Men's Black Cargo Pants",
        "category": "Casual",
        "price": 1083,
        "product_url": "https://www.bewakoof.com/p/mens-black-oversized-cargo-pants",
        "platform": "Bewakoof",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Top Rated",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-black-oversized-cargo-pants-648470-1725879074-1.JPG"
    },
    {
        "id": "bewakoof-casual-f1",
        "name": "Women's Black Oversized T-Shirt",
        "category": "Casual",
        "price": 599,
        "product_url": "https://www.bewakoof.com/p/womens-black-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.4,
        "delivery_days": 2,
        "match_reason": "Bestseller",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-black-typography-back-printed-oversized-t-shirt-481540-1657200745-1.jpg"
    },
    {
        "id": "bewakoof-casual-f7",
        "name": "Women's Pink Graphic Printed Tee",
        "category": "Casual",
        "price": 462,
        "product_url": "https://www.bewakoof.com/p/womens-pink-graphic-printed-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Fun Print",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-pink-graphic-printed-oversized-t-shirt-507302-1658244303-1.jpg"
    },
    {
        "id": "bewakoof-casual-f8",
        "name": "Women's Black Cargo Joggers",
        "category": "Casual",
        "price": 1249,
        "product_url": "https://www.bewakoof.com/p/womens-black-cargo-joggers",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Streetwear Fav",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-black-cargo-joggers-633680-1708949907-1.jpg"
    },
    {
        "id": "bewakoof-casual-f9",
        "name": "Women's Maroon Oversized T-Shirt",
        "category": "Casual",
        "price": 299,
        "product_url": "https://www.bewakoof.com/p/womens-maroon-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.3,
        "delivery_days": 2,
        "match_reason": "Cozy Classic",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-maroon-oversized-t-shirt-507321-1658244660-1.jpg"
    },
    {
        "id": "bewakoof-cm-1",
        "name": "Men's Black Oversized T-Shirt",
        "category": "Casual",
        "price": 519,
        "product_url": "https://www.bewakoof.com/p/mens-black-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Bestseller",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-black-oversized-t-shirt-468585-1643096583-1.jpg"
    },
    {
        "id": "bewakoof-cm-2",
        "name": "Men's Blue Striped Oversized Shirt",
        "category": "Casual",
        "price": 499,
        "product_url": "https://www.bewakoof.com/p/mens-blue-striped-oversized-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Streetwear",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-blue-striped-oversized-shirt-597301-1718599038-1.jpg"
    },
    {
        "id": "bewakoof-cm-3",
        "name": "Men's Grey Relaxed Fit Joggers",
        "category": "Casual",
        "price": 1209,
        "product_url": "https://www.bewakoof.com/p/mens-grey-relaxed-fit-joggers",
        "platform": "Bewakoof",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Comfort Pick",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-grey-relaxed-fit-jogger-479484-1656191270-1.jpg"
    },
    {
        "id": "bewakoof-cm-4",
        "name": "Men's Navy Blue Polo T-Shirt",
        "category": "Casual",
        "price": 699,
        "product_url": "https://www.bewakoof.com/p/mens-navy-blue-polo-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 2,
        "match_reason": "Classic Polo",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-navy-blue-flatknit-polo-t-shirt-634392-1751614201-1.png"
    },
    {
        "id": "bewakoof-cm-5",
        "name": "Men's Maroon Graphic Oversized Tee",
        "category": "Casual",
        "price": 299,
        "product_url": "https://www.bewakoof.com/p/mens-maroon-graphic-printed-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Cool Print",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-maroon-graphic-printed-oversized-t-shirt-509560-1658246480-1.jpg"
    },
    {
        "id": "bewakoof-cm-6",
        "name": "Men's Black Oversized Cargo Pants",
        "category": "Casual",
        "price": 1083,
        "product_url": "https://www.bewakoof.com/p/mens-black-oversized-cargo-pants",
        "platform": "Bewakoof",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Top Rated",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-black-oversized-cargo-pants-648470-1725879074-1.JPG"
    },
    {
        "id": "bewakoof-cm-8",
        "name": "Men's White Oversized T-Shirt",
        "category": "Casual",
        "price": 400,
        "product_url": "https://www.bewakoof.com/p/mens-white-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.3,
        "delivery_days": 2,
        "match_reason": "Clean Basic",
        "gender": "Male",
        "image_url": "https://images.bewakoof.com/original/men-s-white-oversized-t-shirt-525637-1659419308-1.JPG"
    },
    {
        "id": "bewakoof-cf-1",
        "name": "Women's Black Oversized T-Shirt",
        "category": "Casual",
        "price": 599,
        "product_url": "https://www.bewakoof.com/p/womens-black-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.4,
        "delivery_days": 2,
        "match_reason": "Bestseller",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-black-typography-back-printed-oversized-t-shirt-481540-1657200745-1.jpg"
    },
    {
        "id": "bewakoof-cf-2",
        "name": "Women's Pink Graphic Oversized Tee",
        "category": "Casual",
        "price": 462,
        "product_url": "https://www.bewakoof.com/p/womens-pink-graphic-printed-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.3,
        "delivery_days": 3,
        "match_reason": "Fun Print",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-pink-graphic-printed-oversized-t-shirt-507302-1658244303-1.jpg"
    },
    {
        "id": "bewakoof-cf-4",
        "name": "Women's Black Cargo Joggers",
        "category": "Casual",
        "price": 1249,
        "product_url": "https://www.bewakoof.com/p/womens-black-cargo-joggers",
        "platform": "Bewakoof",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Street Fav",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-black-cargo-joggers-633680-1708949907-1.jpg"
    },
    {
        "id": "bewakoof-cf-6",
        "name": "Women's Maroon Oversized T-Shirt",
        "category": "Casual",
        "price": 299,
        "product_url": "https://www.bewakoof.com/p/womens-maroon-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.3,
        "delivery_days": 2,
        "match_reason": "Cozy Classic",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-maroon-oversized-t-shirt-507321-1658244660-1.jpg"
    },
    {
        "id": "bewakoof-cf-7",
        "name": "Women's Blue Oversized Tee",
        "category": "Casual",
        "price": 499,
        "product_url": "https://www.bewakoof.com/p/womens-blue-oversized-t-shirt",
        "platform": "Bewakoof",
        "quality_rating": 4.1,
        "delivery_days": 3,
        "match_reason": "Everyday Wear",
        "gender": "Female",
        "image_url": "https://images.bewakoof.com/original/women-s-blue-oversized-t-shirt-507319-1658246762-1.jpg"
    }
]

HARDCODED_FESTIVE_ITEMS = [
    {
        "id": "myntra-festive-1",
        "name": "Vastramay Men Ethnic Motifs Printed Kurta",
        "category": "Festive",
        "price": 874,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/21689194/2023/1/24/07d3c4b1-4d74-4b7b-95d8-32030fc44c1f1674561019933VastramayMensBeigeCottonBlendKurta1.jpg",
        "product_url": "https://www.myntra.com/kurtas/vastramay/vastramay-men-ethnic-motifs-printed-kurta/21689194/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 3,
        "match_reason": "Ethnic Pick",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-2",
        "name": "Vastramay Men Ethnic Motifs Printed Straight Kurta",
        "category": "Festive",
        "price": 874,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/21689174/2023/1/24/f6e3466e-f9e8-4243-9a6b-7d9609cee5351674560617277VastramayMensOrangeCottonBlendKurta1.jpg",
        "product_url": "https://www.myntra.com/kurtas/vastramay/vastramay-men-ethnic-motifs-printed-straight-kurta/21689174/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Ethnic Pick",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-3",
        "name": "Vastramay Men Ethnic Motifs Thread Work Kurta",
        "category": "Festive",
        "price": 874,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/21689168/2023/1/24/3c912b3a-699f-411c-8b40-7f8824201a4d1674559955663VastramayMensPinkCottonBlendKurta1.jpg",
        "product_url": "https://www.myntra.com/kurtas/vastramay/vastramay-men-ethnic-motifs-thread-work-kurta/21689168/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 4,
        "match_reason": "Premium Finish",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-4",
        "name": "Klotthe Men Blue Ethnic Motifs Kurta",
        "category": "Festive",
        "price": 1298,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/productimage/2021/2/9/0612aadf-2ab8-4c5d-805c-00462cf86d641612858078151-1.jpg",
        "product_url": "https://www.myntra.com/kurtas/klotthe/klotthe-men-blue-ethnic-motifs-kurta/13616782/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 5,
        "match_reason": "Stylish Blue",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-5",
        "name": "Klotthe Men Navy Blue Gold Woven Kurta",
        "category": "Festive",
        "price": 749,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/productimage/2020/9/17/96c85007-7afe-463f-8d5b-cb068c383d5a1600293638948-1.jpg",
        "product_url": "https://www.myntra.com/kurtas/klotthe/klotthe-men-navy-blue--gold-coloured-woven-design-a-line-kurta/12486434/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Trending Ethnic",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-6",
        "name": "Manthan Men Woven Design Thread Work Kurta",
        "category": "Festive",
        "price": 999,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/27620772/2024/2/26/74559365-e17a-426c-98f1-30e1e25dad281708940511147-Manthan-Beige-Art-Silk-Self-Design-Kurtas-for-Men-9231708940-1.jpg",
        "product_url": "https://www.myntra.com/kurtas/manthan/manthan-men-woven-design-thread-work-kurta/27620772/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 2,
        "match_reason": "Premium Choice",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-7",
        "name": "Sangria Men Floral Printed Kurta",
        "category": "Festive",
        "price": 1247,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/SEPTEMBER/9/FkRXyxi1_fd8fd0b91bcd4f8fb03a0675c696bcb7.jpg",
        "product_url": "https://www.myntra.com/kurtas/sangria/sangria-men-floral-printed-kurta/36877149/buy",
        "platform": "Myntra",
        "quality_rating": 4.1,
        "delivery_days": 4,
        "match_reason": "Stylish Floral",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-8",
        "name": "Here&now x Sanwara Mandarin Collar Jacquard Kurta",
        "category": "Festive",
        "price": 1184,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/29116822/2024/4/24/2ef542a8-aed5-43be-8d50-a35a079a58031713940679204SanwaraMenThreadWorkKurta1.jpg",
        "product_url": "https://www.myntra.com/kurtas/here%26now+x+sanwara/herenow-x-sanwara--mandarin-collar-woven-design-thread-work-jacquard-straight-kurta/29116822/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 3,
        "match_reason": "Luxury Velvet/Jacquard",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-9",
        "name": "Here&now x Sanwara Men Yellow Woven Straight Kurta",
        "category": "Festive",
        "price": 2699,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/6766779/2018/6/19/fc09d526-37da-49dc-8ef7-4860d05e8e861529374158094-na-9491529374157807-1.jpg",
        "product_url": "https://www.myntra.com/kurtas/here%26now+x+sanwara/herenow-x-sanwara--men-yellow-woven-design-straight-kurta/6766779/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Haldi Pick",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-10",
        "name": "The Kurta Company Abstract Printed Mandarin Straight Kurta",
        "category": "Festive",
        "price": 2343,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2024/AUGUST/24/82rtbIEQ_0a4ce0504b964bc7aedfac7f1ae30385.jpg",
        "product_url": "https://www.myntra.com/kurtas/the+kurta+company/the-kurta-company-abstract-printed-mandarin-collar-straight-kurta/30704401/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 4,
        "match_reason": "Myntra Favorite",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-11",
        "name": "Manyavar Men Woven Design Mandarin Collar Kurta",
        "category": "Festive",
        "price": 2199,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/NOVEMBER/15/Soc3R8rM_46ee851096db48e58b02614b8925336f.jpg",
        "product_url": "https://www.myntra.com/kurtas/manyavar/manyavar-men-woven-design-mandarin-collar-self-design-foil-print-kurta/29916067/buy",
        "platform": "Myntra",
        "quality_rating": 4.9,
        "delivery_days": 3,
        "match_reason": "Ultimate Shaadi Choice",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-12",
        "name": "Moshi Geometric Printed Pure Cotton Straight Kurta",
        "category": "Festive",
        "price": 3499,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2024/AUGUST/27/HjcXCRCc_c5a12bacce8749adaf753a2c20269d0b.jpg",
        "product_url": "https://www.myntra.com/kurtas/moshi/moshi-geometric-printed-pure-cotton-straight-kurta/30729360/buy",
        "platform": "Myntra",
        "quality_rating": 4.2,
        "delivery_days": 4,
        "match_reason": "Comfort Pick",
        "gender": "Male"
    },
    {
        "id": "myntra-festive-13",
        "name": "Pulseiq Men Embroidered Thread Work Cotton Straight Kurta",
        "category": "Festive",
        "price": 898,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/OCTOBER/7/ntGDszZ2_6624bec7903d4bad921b10e3c2f6d86d.jpg",
        "product_url": "https://www.myntra.com/kurtas/pulseiq/pulseiq-men-embroidered-thread-work-mandarin-collar-cotton-straight-kurta/37361316/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 2,
        "match_reason": "Modern Ethnic",
        "gender": "Male"
    },
    {
        "id": "myntra-womens-festive-1",
        "name": "Sangria Ethnic Motifs Printed Saree",
        "category": "Festive",
        "price": 1199,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/MAY/30/RcWsH1Qi_14de1927d654451b8bd61a02e02ba5d8.jpg",
        "product_url": "https://www.myntra.com/sarees/sangria/sangria-ethnic-motifs-printed-saree-with-blouse-piece/34572213/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 4,
        "match_reason": "Womens Festive Essential",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-2",
        "name": "Sangria Ethnic Printed Bandhani Saree",
        "category": "Festive",
        "price": 797,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JANUARY/3/BIPQoSx4_87ec5252ba92494092383ca6c25ca9de.jpg",
        "product_url": "https://www.myntra.com/sarees/sangria/sangria-ethnic-printed-bandhani-saree-with-blouse-piece/32196518/buy",
        "platform": "Myntra",
        "quality_rating": 4.4,
        "delivery_days": 3,
        "match_reason": "Vibrant Festive",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-3",
        "name": "Anouk Colourblocked Printed Tissue Saree",
        "category": "Festive",
        "price": 1242,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/APRIL/14/T3SOaGn9_6587fbc2ab1a47aaa9d923448e592f9f.jpg",
        "product_url": "https://www.myntra.com/sarees/anouk/anouk-colourblocked-printed-tissue-saree/33589217/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 2,
        "match_reason": "Elegant Festive Choice",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-4",
        "name": "Saree Mall Striped Zari Pure Georgette Saree",
        "category": "Festive",
        "price": 1792,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/JUNE/5/4NeOajnR_d03dda73942a4ef299ff054ab69c3d6e.jpg",
        "product_url": "https://www.myntra.com/sarees/saree+mall/saree-mall-striped-zari-pure-georgette-saree/34747658/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 3,
        "match_reason": "Premium Ethnic",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-5",
        "name": "Sangria Navy Blue Ethnic Motifs A-line Kurta",
        "category": "Festive",
        "price": 2183,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/30271855/2024/7/20/fc97cfb5-4c60-4675-9c7e-a0fde116e2a41721448915014SangriaEmbroideredA-LineKurtaWithTrouserDupattaSet1.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/sangria/sangria-navy-blue-ethnic-motifs-embroidered-a-line-kurta-with-trouser--dupatta/30271855/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 4,
        "match_reason": "Must-have Kurta Set",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-6",
        "name": "Indo Era Embroidered Mandarin Collar Kurta",
        "category": "Festive",
        "price": 2391,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/32703706/2025/2/15/4ceae496-2a9a-44a4-8b3e-ab6591901a771739602757779-Indo-Era-Embroidered-Mandarin-Collar-Pure-Cotton-A-Line-Kurt-1.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/indo+era/indo-era-embroidered-mandarin-collar-pure-cotton-a-line-kurta-with-trouser--dupatta/32703706/buy",
        "platform": "Myntra",
        "quality_rating": 4.6,
        "delivery_days": 3,
        "match_reason": "Festive Favourite",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-7",
        "name": "House of Pataudi Ethnic Motifs Kurta",
        "category": "Festive",
        "price": 2199,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/25236206/2023/9/26/ce438488-b1ed-4b96-8b40-b8b1513d6d431695716803764PinkEmbroideredWovenDesignStraightKurtaandTrousersWithDupatt7.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/house+of+pataudi/house-of-pataudi-ethnic-motifs-embroidered-straight-kurta-with-trousers--dupatta/25236206/buy",
        "platform": "Myntra",
        "quality_rating": 4.9,
        "delivery_days": 2,
        "match_reason": "Luxurious Festive",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-8",
        "name": "Libas Floral Embroidered Kurta",
        "category": "Festive",
        "price": 1689,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/33460634/2025/4/16/a86fb7d2-716c-4831-b50f-5003d6cc8d181744795485358-Libas-Women-Floral-Embroidered-Regular-Sequinned-Kurta-with--1.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/libas/libas-women-floral-embroidered-regular-sequinned-kurta-with-trousers--with-dupatta/33460634/buy",
        "platform": "Myntra",
        "quality_rating": 4.8,
        "delivery_days": 3,
        "match_reason": "Sequinned Festive Wear",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-9",
        "name": "Indo Era Ethnic Motifs Embroidered Kurta",
        "category": "Festive",
        "price": 2379,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/27580842/2024/2/13/eb0fcf8f-7f2d-4c92-83fd-50a7186381d01707832035402IndoEraRedEmbroideredStraightKurtaTrousersWithDupattaSet1.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/indo+era/indo-era-ethnic-motifs-embroidered-thread-work-kurta-with-trousers--dupatta/27580842/buy",
        "platform": "Myntra",
        "quality_rating": 4.5,
        "delivery_days": 5,
        "match_reason": "Intricate Thread Work",
        "gender": "Female"
    },
    {
        "id": "myntra-womens-festive-10",
        "name": "Sangria Floral Embroidered Notch Neck Kurta",
        "category": "Festive",
        "price": 1998,
        "image_url": "https://assets.myntassets.com/h_1080,q_80,w_720/h_1440,q_75,w_1080/v1/assets/images/2025/FEBRUARY/12/Z5VEWa9d_822f47556e124630a2df39ddc3c86993.jpg",
        "product_url": "https://www.myntra.com/kurta-sets/sangria/sangria-floral-embroidered-panelled-notch-neck-a-line-kurta-with-trouser-and-dupatta/32726706/buy",
        "platform": "Myntra",
        "quality_rating": 4.7,
        "delivery_days": 2,
        "match_reason": "Popular Festival Choice",
        "gender": "Female"
    }
]

